# Generated by Django 3.2.5 on 2021-07-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0002_auto_20210630_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hikerecommendation',
            name='hike_img',
        ),
        migrations.AddField(
            model_name='hikelocation',
            name='hike_img',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
