# Generated by Django 3.2.5 on 2021-07-07 20:38

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0003_auto_20210701_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hikelocation',
            name='hike_address',
        ),
        migrations.RemoveField(
            model_name='hikelocation',
            name='hike_img',
        ),
        migrations.RemoveField(
            model_name='hikelocation',
            name='hike_lat',
        ),
        migrations.RemoveField(
            model_name='hikelocation',
            name='hike_lng',
        ),
        migrations.AddField(
            model_name='hikelocation',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hikelocation',
            name='hike_name',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
    ]
