# Generated by Django 3.2.5 on 2021-07-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0004_auto_20210707_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hikelocation',
            old_name='hike_name',
            new_name='address',
        ),
    ]
