# Generated by Django 3.2.5 on 2021-07-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0005_rename_hike_name_hikelocation_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hikelocation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hikelocation',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='hikelocation',
            name='hike_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hikelocation',
            name='hike_img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hikelocation',
            name='hike_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hikelocation',
            name='hike_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hikelocation',
            name='hike_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
