# Generated by Django 3.2.5 on 2021-07-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0007_auto_20210712_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='hike_weather_rating',
        ),
        migrations.RemoveField(
            model_name='hikerecommendation',
            name='weather_rating',
        ),
    ]
